version: "3.0"

networks:
  metrics:
    name: metrics

services:
  docker-prometheus-grafana:
    build: .
    ports:
      - 8080:8080
    networks:
      - metrics

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - metrics

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - metrics